### ISSUE TITLE
Incorrect type for the return types of `send*` methods

### ISSUE THREAD

**Issue by roj1512** [grammyjs/types#39]
Any `send*` methods that is used for sending media files, except photos, are subject to return messages of any type, rendering the custom `*Message` types useless.

**Comment by roj1512** [comment]
Maybe this is just to be fixed in the core repo? Change `DocumentMessage` in the return type of `sendDocument` to `DocumentMessage | StickerMessage`.

**Comment by KnorpelSenf** [comment]
> Maybe this is just to be fixed in the core repo?

The types are defined here, and only here: https://github.com/grammyjs/types/blob/fbbb7c54c0b67cd9e168d5584b0e993d05db3fe3/methods.ts#L343

> Change `DocumentMessage` in the return type of `sendDocument` to `DocumentMessage | StickerMessage`.

That would describe something undocumented.

> Any `send*` methods that is used for sending media files, except photos, are subject to return messages of any type

That is correct. This is a known and intended inconsistency between the types and the specs.

In 99 % of cases, the returned message object contains exactly what is expected. This leaves us with two options:
1. Follow the specs very closely. Use `Message`. Upside: correctness in the 1 % of cases. Downside: worse usability in the other 99 %.
2. Do the intuitive and mostly correct thing. The current way. Use `Message.DocumentMessage` etc. Upside: good usability, downside: not quite correct.

Currently, grammY does number 2. Telegraf used to have types that are very hard to use in order to be highly accurate. grammY way supposed to improve this by making reasonable compromises, trading in some correctness for a lot of usability. Being practical about such things is the vastly more successful model, however, in this particular instance, I have indeed often thought that I should've went with option 1 instead. I might reconsider this for the next major version of grammY.

> rendering the custom `*Message` types useless.

That is not correct. They are useful in bot code in any case, no matter if they're used as return types or not.

**Comment by roj1512** [comment]
The goal of types is to not allow broken code to run. Closing this anyway.
