### ISSUE TITLE
Add types for window.Telegram.WebApp object

### ISSUE THREAD

**Issue by ansavchenco** [grammyjs/types#9]
According to the [Telegram Bot API Web Apps documentation](https://core.telegram.org/bots/webapps#initializing-web-apps), if you want to access data from the Telegram bot in your web app, you have to load some special script provided by Telegram that populates `window.Telegram.WebApp` object. However, `grammY` does not provide types for that object. Maybe it's a good idea to include them too?

**Comment by KnorpelSenf** [comment]
This repository contains types for the Bot API. The types you're describing aren't part of that API. They're part of web apps, which have their own API provided by each Telegram client.

grammY does provide these types in the web app repo, see https://github.com/grammyjs/web-app. Note that we outsourced the actual type definitions to DefinitelyTyped so that it's possible to use the raw API without our convenience package.
